name: dona
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The follow ing defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_libphonenumber: ^2.2.1

  # Others
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_advanced_avatar: ^1.5.0
  group_button: ^5.3.4  
  flutter_map: ^6.1.0
  flutter_map_tile_caching: ^9.0.1
  latlong2: ^0.9.1
  align_positioned: ^4.0.1
  animate_do: ^3.3.4
  pattern_formatter: ^3.0.0
  bouncing_widget: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/user/
    - assets/images/vice/
    - assets/images/on_boarding_images/
    - assets/images/illustrations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/users/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          # width: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          # width: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          # width: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          # width: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          # width: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          # width: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          # width: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          # width: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          # width: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          # width: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          # width: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          # width: 700
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          # width: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          # width: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          # width: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          # width: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          # width: 900
          style: italic

  # see https://flutter.dev/custom-fonts/#from-packages
